### ISSUE TITLE
Cannot Pick Up swords from stones

### ISSUE THREAD

**Issue by DerPizzaBursche** [BrownBear85/swordinthestone#1]
I've tested your mod, but I cannot pick up any sword. I tested it in many saves but it didn't worked. I tried destroying the stone, right and left clicking, shift clicking. Am I doing something wrong or is it currently not working?

**Comment by hanchii18** [comment]
Any detailed instruction on how to pick up the sword?

**Comment by DayIsGone** [comment]
> Any detailed instruction on how to pick up the sword?



> I've tested your mod, but I cannot pick up any sword. I tested it in many saves but it didn't worked. I tried destroying the stone, right and left clicking, shift clicking. Am I doing something wrong or is it currently not working?

you can pull it I looked through the mod files to figure it out and you have to cycle through left and right clicks with your mouse to shake it. after shaking it a specific amount of times it will let you have the sword

**Comment by BrownBear85** [comment]
Mb for being unclear lol. To pull out the sword, hold right click or repeatedly click 40 times. I'll make it more clear in a future update.
