### ISSUE TITLE
[bug][neoforge] Unbreakable swords instantly break

### ISSUE THREAD

**Issue by LDiarth** [BrownBear85/swordinthestone#9]
Version:
Sword In the Stone 2.1
NeoForge 21.0.148

Expected behaviour:
Setting the sword durability to 0 in the config makes the swords unbreakable.

Actual behaviour:
Setting the sword durability to 0 in the config makes the swords break after a single use.

**Comment by BrownBear85** [comment]
Thanks for letting me know. It was caused by a strange change in vanilla's code when I ported from 1.20 -> 1.21. I will upload a fixed 1.21 jar soon.
